### ISSUE TITLE
User Auth MVP

### ISSUE THREAD

**Issue by JanViefhues** [JanViefhues/medium_fullstack#7]
- [ ] Backend: DB, model, controller, views
- [ ] Redux Loop: ajax, actions, reducer
- [ ] Presentational Components and Containers
- [ ] Styling
- [ ] Smooth, bug-free navigation
- [ ] Adequate and appropriate seeds

**Comment by linakherchi** [comment]
Hi Jan, could you please update the link on your wiki page to mirror your Heroku app ? Thank you !
